---
# Source: trilium/templates/config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: trilium-config
  labels:
    app.kubernetes.io/instance: trilium
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: trilium
    app.kubernetes.io/version: 0.92.4
    helm.sh/chart: trilium-1.3.0
data:
  config.ini: |
    [General]
    # Instance name can be used to distinguish between different instances using backend api.getInstanceName()
    instanceName=

    # set to true to allow using Trilium without authentication (makes sense for server build only, desktop build doesn't need password)
    noAuthentication=false

    # set to true to disable backups (e.g. because of limited space on server)
    noBackup=false

    # Disable automatically generating desktop icon
    # noDesktopIcon=true

    [Network]
    # host setting is relevant only for web deployments - set the host on which the server will listen
    host=0.0.0.0
    # port setting is relevant only for web deployments, desktop builds run on a fixed port (changeable with TRILIUM_PORT environment variable)
    port=8080
    # true for TLS/SSL/HTTPS (secure), false for HTTP (unsecure).
    https=false
    # path to certificate (run "bash bin/generate-cert.sh" to generate self-signed certificate). Relevant only if https=true
    certPath=
    keyPath=
    # setting to give trust to reverse proxies, a comma-separated list of trusted rev. proxy IPs can be specified (CIDR notation is permitted),
    # alternatively 'true' will make use of the leftmost IP in X-Forwarded-For, ultimately an integer can be used to tell about the number of hops between
    # Trilium (which is hop 0) and the first trusted rev. proxy.
    # once set, expressjs will use the X-Forwarded-For header set by the rev. proxy to determinate the real IPs of clients.
    # expressjs shortcuts are supported: loopback(127.0.0.1/8, ::1/128), linklocal(169.254.0.0/16, fe80::/10), uniquelocal(10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, fc00::/7)
    trustedReverseProxy=true
---
# Source: trilium/templates/release.yaml
apiVersion: v1
kind: Service
metadata:
  name: trilium
  labels:
    app.kubernetes.io/instance: trilium
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: trilium
    app.kubernetes.io/service: trilium
    app.kubernetes.io/version: 0.92.4
    helm.sh/chart: trilium-1.3.0
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: main
    app.kubernetes.io/instance: trilium
    app.kubernetes.io/name: trilium
---
# Source: trilium/templates/release.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trilium
  labels:
    app.kubernetes.io/component: main
    app.kubernetes.io/instance: trilium
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: trilium
    app.kubernetes.io/version: 0.92.4
    helm.sh/chart: trilium-1.3.0
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/component: main
      app.kubernetes.io/name: trilium
      app.kubernetes.io/instance: trilium
  template:
    metadata:
      labels: 
        app.kubernetes.io/component: main
        app.kubernetes.io/instance: trilium
        app.kubernetes.io/name: trilium
    spec: 
      enableServiceLinks: false
      serviceAccountName: default
      automountServiceAccountToken: true
      hostIPC: false
      hostNetwork: false
      hostPID: false
      dnsPolicy: ClusterFirst
      initContainers: 
        - args:
          - sh
          - -c
          - chown -R 1000:1000 /home/node/trilium-data
          image: busybox:latest
          name: fixperms
          securityContext:
            runAsGroup: 0
            runAsUser: 0
          volumeMounts:
          - mountPath: /home/node/trilium-data
            name: data
      containers: 
        - env:
          - name: key
            value: value
          image: triliumnext/notes:v0.95.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 10
          name: trilium
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 10
          startupProbe:
            failureThreshold: 10
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 10
            timeoutSeconds: 5
          volumeMounts:
          - mountPath: /home/node/trilium-data/config.ini
            name: config
            subPath: config.ini
          - mountPath: /home/node/trilium-data
            name: data
      volumes: 
        - configMap:
            name: trilium-config
          name: config
        - name: data
          persistentVolumeClaim:
            claimName: trilium-data
---
# Source: trilium/templates/release.yaml
# Merge with ALL the values in `values.yaml`
