apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trilium-data
  namespace: trilium
spec:
  accessModes:
    - ReadWriteMany          # 위 PV와 맞춰야 함
  resources:
    requests:
      storage: 64Gi
  volumeName: trilium-nfs-pv  # 이 PV랑 직접 바인딩

