apiVersion: v1
data:
  config.ini: |
    [General]
    # Instance name can be used to distinguish between different instances using backend api.getInstanceName()
    instanceName=

    # set to true to allow using Trilium without authentication (makes sense for server build only, desktop build doesn't need password)
    noAuthentication=false

    # set to true to disable backups (e.g. because of limited space on server)
    noBackup=false

    # Disable automatically generating desktop icon
    # noDesktopIcon=true

    [Network]
    # host setting is relevant only for web deployments - set the host on which the server will listen
    host=0.0.0.0
    # port setting is relevant only for web deployments, desktop builds run on a fixed port (changeable with TRILIUM_PORT environment variable)
    port=8080
    # true for TLS/SSL/HTTPS (secure), false for HTTP (unsecure).
    https=false
    # path to certificate (run "bash bin/generate-cert.sh" to generate self-signed certificate). Relevant only if https=true
    certPath=
    keyPath=
    # setting to give trust to reverse proxies, a comma-separated list of trusted rev. proxy IPs can be specified (CIDR notation is permitted),
    # alternatively 'true' will make use of the leftmost IP in X-Forwarded-For, ultimately an integer can be used to tell about the number of hops between
    # Trilium (which is hop 0) and the first trusted rev. proxy.
    # once set, expressjs will use the X-Forwarded-For header set by the rev. proxy to determinate the real IPs of clients.
    # expressjs shortcuts are supported: loopback(127.0.0.1/8, ::1/128), linklocal(169.254.0.0/16, fe80::/10), uniquelocal(10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, fc00::/7)
    trustedReverseProxy=true
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: trilium
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: trilium
    app.kubernetes.io/version: 0.92.4
    helm.sh/chart: trilium-1.3.0
  name: trilium-config
  namespace: trilium
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: trilium
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: trilium
    app.kubernetes.io/service: trilium
    app.kubernetes.io/version: 0.92.4
    helm.sh/chart: trilium-1.3.0
  name: trilium
  namespace: trilium
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/component: main
    app.kubernetes.io/instance: trilium
    app.kubernetes.io/name: trilium
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: trilium-nfs-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  nfs:
    path: /mnt/hs-nas-zfs/dev-trilium-storage
    server: 192.168.0.75
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trilium-data
  namespace: trilium
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: trilium-nfs-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: main
    app.kubernetes.io/instance: trilium
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: trilium
    app.kubernetes.io/version: 0.92.4
    helm.sh/chart: trilium-1.3.0
  name: trilium
  namespace: trilium
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/component: main
      app.kubernetes.io/instance: trilium
      app.kubernetes.io/name: trilium
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: main
        app.kubernetes.io/instance: trilium
        app.kubernetes.io/name: trilium
    spec:
      automountServiceAccountToken: true
      containers:
      - env:
        - name: key
          value: value
        image: triliumnext/trilium:v0.99.5
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /login
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 10
        name: trilium
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /login
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
        startupProbe:
          failureThreshold: 10
          httpGet:
            path: /login
            port: 8080
          initialDelaySeconds: 45
          periodSeconds: 10
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: /home/node/trilium-data/config.ini
          name: config
          subPath: config.ini
        - mountPath: /home/node/trilium-data
          name: data
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      hostIPC: false
      hostNetwork: false
      hostPID: false
      initContainers:
      - args:
        - sh
        - -c
        - chown -R 1000:1000 /home/node/trilium-data
        image: busybox:latest
        name: fixperms
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        securityContext:
          runAsGroup: 0
          runAsUser: 0
        volumeMounts:
        - mountPath: /home/node/trilium-data
          name: data
      serviceAccountName: default
      volumes:
      - configMap:
          name: trilium-config
        name: config
      - name: data
        persistentVolumeClaim:
          claimName: trilium-data
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: trilium-gateway
  namespace: trilium
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: trilium
  namespace: trilium
spec:
  gateways:
  - trilium-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: trilium
        port:
          number: 8080
---
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: trilium-telemetry
  namespace: trilium
spec:
  accessLogging:
  - providers:
    - name: envoy
  metrics:
  - providers:
    - name: prometheus
  tracing:
  - providers:
    - name: zipkin
