apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: trilium

resources:
  - ../../base
  - pv.yaml
  - pvc.yaml
  - gateway.yaml
  - virtualservice.yaml
  - telemetry.yaml

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: trilium
